---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  labels:
    {{- with .Values.extraLabels }}
     {{ toYaml . | nindent 4}}
    {{- end }}  
    {{- include "helm.labels" . | nindent 4 }}  