---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  labels:
    {{- with .Values.extraLabels }}
     {{ toYaml . | nindent 4}}
    {{- end }}  
    {{- include "helm.labels" . | nindent 4 }}  
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  labels:
    {{- with .Values.extraLabels }}
     {{ toYaml . | nindent 4}}
    {{- end }}  
    {{- include "helm.labels" . | nindent 4 }}   
stringData:
  slack-token: {{ required "A valid slack token is required!" .Values.slack.token }}