---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: argocd-notifications-controller-metrics
  name: argocd-notifications-controller-metrics
  labels:
    {{- with .Values.extraLabels }}
     {{ toYaml . | nindent 4}}
    {{- end }}  
    {{- include "helm.labels" . | nindent 4 }}  
spec:
  ports:
  - name: metrics
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app.kubernetes.io/name: argocd-notifications-controller