---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
    {{- with .Values.extraLabels }}
     {{ toYaml . | nindent 4}}
    {{- end }}  
    {{- include "helm.labels" . | nindent 4 }}     
  name: argocd-secret
type: Opaque


---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    {{- with .Values.extraLabels }}
      {{ toYaml . | nindent 4}}
    {{- end }} 
    {{- include "helm.labels" . | nindent 4 }}    
  name: {{ .Values.repoName }}
  namespace: {{ .Values.nameSpace }}
type: Opaque
data:
  password: {{ .Values.secret.password | b64enc }}
  username: {{ .Values.secret.username | b64enc }}